server:
  port: 9090
greeting: Hello
greetings:
  EN: Hello
  ES: Hola
  DE: Hallo
  CN: 你好
user:
  name: Chaos
  gender: male
  age: ${random.int}
product:
  name: picture
  seller: chaos
  price: 12.3
  weight: 2
order:
  id: 1234d5
  paid: 123